### ISSUE TITLE
any aptx adaptive lib

### ISSUE THREAD

**Issue by long45343** [Flex1911/aptx-libs-android10#1]
i have a Bluetooth device support aptx adaptive but my device didn't have this.

**Comment by Flex1911** [comment]
aptX Adaptive is a different fruit. It needs framework-side support and a different Bluetooth stack to work.

**Comment by long45343** [comment]
so may snapdragon 625 have chance to use aptx adaptive？

**Comment by Flex1911** [comment]
No. aptX adaptive is only supported on recent SoCs which support A2DP offload (2018 and newer)
